name: misis-analytics-build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install bootstrap & build wheels
        run: |
          pip install --upgrade pip
          pip install -e build/misis_bootstrap
          misis-bootstrap

      - name: Lint with ruff & flake8
        run: |
          pip install ruff flake8
          ruff check source/
          flake8 --max-line-length 120 build/ source/

      - name: Build Docker images & run all tests
        run: |
          cd build/docker
          python build_all.py -c images_configuration.json --test
