name: misis-analytics-build

on:
  push: { branches: ['**'] }
  pull_request: { branches: ['**'] }

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apply linters
        run: |
          pip install ruff flake8
          ruff check source/
          flake8 --max-line-length 120 build/ source/
      - name: build images and test
        run: |
          cd build/docker
          python build_all.py -c images_configuration.json --test
